proyecto/Areas/Admin/Controllers/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using Helper;
using System.IO;

using proyecto.Areas.Admin.Filters;

namespace proyecto.Areas.Admin.Controllers
{

    [Autenticado]
    public class PerfilController : Controller
    {

        private Usuario usuario = new Usuario();
        // GET: Admin/Perfil
        public ActionResult Miperfil()
        {
            return View(usuario.ObtenerPerfil(SessionHelper.GetUser()));
        }


        public JsonResult GuardarPerfil(Usuario model, HttpPostedFileBase foto)
        {
            var rm = new ResponseModel();

            //Para Validar que el campo Pasword Nose Guarde
            ModelState.Remove("clave");
            if (ModelState.IsValid)
            {
                rm = model.GuardarPerfil(foto);
            }

            return Json(rm);
        }
        
    }
}

proyecto/Areas/Admin/Views/Perfil/MiPerfil.cshtml
@model Usuario
  
@{
    ViewBag.Title = (Model.idusuario > 0 ? Model.nombre : "Nuevo registro");
}

<link href="~/Areas/Admin/Assets/css/styleimg.css" rel="stylesheet" />

@using (Html.BeginForm("GuardarPerfil", "Perfil", FormMethod.Post))
{


<div class="row">
    <div class="col-md-3">

        <div class="well">
            <div class="form-group">
                <img src="~/Areas/Admin/img/@Model.foto"  class="mediana">
            </div>

            <div class="form-group">
                <div class="form-group">
                    <label>Actualizar Foto De Perfil</label>
                    <input type="file" name="foto" />
                </div>
            </div>

        </div>

    </div>



    <div class="col-sm-8 col-md-8">
        <div class="well">
            <div id="yo" class="page">

              
                <div>
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab">Información de Usuario</a></li>
                    
                    </ul>


                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" style="scrollbar-base-color:ButtonHighlight aliceblue;" id="info">
                           
                            <div class="form-horizontal">
                                <p></p>
                                <fieldset>

                                   
                                    <div class="form-group">
                                        @Html.HiddenFor(x => x.idusuario)
                                       
                                        @Html.LabelFor(x => x.nombre , new { @class = "col-sm-2 control-label pull-left" } )

                                        <div class="col-md-6">
                                            @Html.TextBoxFor(x => x.nombre, new { @class = "input-12", placeholder = "Ingrese su nombre" })
                                            @Html.ValidationMessageFor(x => x.nombre, null, new { @class = "label label-danger" })
                                        </div>
                                    </div>

                                 

                                        <div class="form-group">
                                            @Html.LabelFor(x => x.correo, new { @class = "col-sm-2 control-label pull-left" })
                                            <div class="col-md-6">
                                                @Html.TextBoxFor(x => x.correo, new { @class = "input-12", placeholder = "Ingrese su nombre" })
                                                @Html.ValidationMessageFor(x => x.correo, null, new { @class = "label label-danger" })
                                            </div>
                                        </div>

                                        @Html.HiddenFor(x => x.clave)

                                        <div class="form-group">
                                            @Html.LabelFor(x => x.telefono, new { @class = "col-sm-2 control-label pull-left" })
                                            <div class="col-md-6">
                                                @Html.TextBoxFor(x => x.telefono, new { @class = "input-12", placeholder = "Ingrese su nombre" })
                                                @Html.ValidationMessageFor(x => x.telefono, null, new { @class = "label label-danger" })
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            @Html.LabelFor(x => x.razonsocial, new { @class = "col-sm-2 control-label pull-left" })
                                            <div class="col-md-6">
                                                @Html.TextBoxFor(x => x.razonsocial, new { @class = "input-12", placeholder = "Ingrese su nombre" })
                                                @Html.ValidationMessageFor(x => x.razonsocial, null, new { @class = "label label-danger" })
                                            </div>
                                        </div>



                                        <div class="form-group">
                                            @Html.LabelFor(x => x.activo, new { @class = "col-sm-2 control-label pull-left" })
                                            <div class="col-md-6">
                                                @Html.TextBoxFor(x => x.activo, new { @class = "input-12", placeholder = "Ingrese su nombre" })
                                                @Html.ValidationMessageFor(x => x.activo, null, new { @class = "label label-danger" })
                                            </div>
                                        </div>

                                      



                            </fieldset>
                            </div>

                        </div>

                    </div>

                </div>

                <div class="text-right well well-sm">
                    <button data-ajax="true" type="submit" class="btn btn-primary">Guardar</button>
                </div>

              

            </div>

        </div>

    </div>

    
               
</div>

    }