proyecto/Areas/Admin/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;

using Helper;
using proyecto.Areas.Admin.Filters;
namespace proyecto.Areas.Admin.Controllers
{

    [Autenticado]
    public class UsuarioController : Controller
    {

   
        private Usuario usuario = new Usuario();
        private Empresa miempresalista = new Empresa();
        // GET: Admin/Usuario
        public ActionResult Index()
        {

           
            return View();
        }

        public JsonResult cargarUsuario(AnexGRID grid)
        {
            return Json(usuario.Listar(grid));
        }

        public ActionResult Crud(int id = 0)
        {
            ViewBag.miempresa = miempresalista.ListarEmpresa();
            return View(
                id == 0 ? new Usuario()
                        : usuario.Obtener(id)
            );
            
        }

        public JsonResult Guardar(Usuario model)
        {
            var rm = new ResponseModel();

            if (ModelState.IsValid)
            {
                rm = model.Guardar();

                if (rm.response)
                {
                    rm.href = Url.Content("~/Admin/usuario/");
                }
            }

            return Json(rm);
        }

        public ActionResult Eliminar(int id)
        {
            usuario.idusuario = id;
            usuario.Eliminar();
            return Redirect("~/admin/usuario/");
        }






    }
}

proyecto/Areas/Admin/Views/Usuario/Crud.cshtml
@model Usuario
@{
    ViewBag.Title = "Crud";
    List<Empresa> empresas = ViewBag.miempresa;
}


@using (Html.BeginForm("Guardar", "Usuario", FormMethod.Post))
{


    <div class="row">



        <div class="col-sm-12 col-md-12">
            <div class="well">
                <div id="yo" class="page">


                    <div>
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab">Información de Usuario</a></li>

                        </ul>


                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" style="scrollbar-base-color:ButtonHighlight aliceblue;" id="info">

                                <div class="form-horizontal">
                                    <p></p>
                                    <fieldset>
                                        <div class="form-group">
                                            @Html.HiddenFor(x => x.idusuario)
                                            @Html.LabelFor(x => x.nombre, new { @class = "col-sm-2 control-label pull-left" })

                                            <div class="col-md-4">
                                                @Html.TextBoxFor(x => x.nombre, new { @class = "input-12", placeholder = "Nombre" })
                                                @Html.ValidationMessageFor(x => x.nombre, null, new { @class = "label label-danger" })
                                            </div>


                                            @*<div class="col-md-4">
                                                @Html.DropDownList("razonsocial", new SelectList(ViewBag.empresas, "idempresa", "nmempresa"), "Seleccionar Empresa", new { @class = "form-control" })

                                                </div>*@
                                                @*@Html.LabelFor(x => x.razonsocial, new { @class = "col-sm-1 control-label pull-left" })
            <div class="col-md-4">
                @Html.TextBoxFor(x => x.razonsocial, new { @class = "input-12", placeholder = "Empresa" })
                @Html.ValidationMessageFor(x => x.razonsocial, null, new { @class = "label label-danger" })
            </div>*@







                                                <div class="form-group">
                                                    <div class="col-md-3">
                                                        <select class="input-12" name="razonsocial">
                                                            @foreach (var c in empresas)
                                                            {
                                                                <option @(Model.razonsocial == (c.nmempresa) ? "selected" : "") value="@c.nmempresa">@c.nmempresa</option>
                                                            }
                                                        </select>
                                                    </div>
                                                </div>

                                            </div>



                                        <div class="form-group">
                                            @Html.LabelFor(x => x.correo, new { @class = "col-sm-2 control-label pull-left" })
                                            <div class="col-md-2">
                                                @Html.TextBoxFor(x => x.correo, new { @class = "input-12", placeholder = "Correo" })
                                                @Html.ValidationMessageFor(x => x.correo, null, new { @class = "label label-danger" })
                                            </div>

                                            @Html.LabelFor(x => x.clave, new { @class = "col-sm-1 control-label pull-left" })
                                            <div class="col-md-3">
                                                @Html.TextBoxFor(x => x.clave, new { @class = "input-12", placeholder = "Clave" })
                                                @Html.ValidationMessageFor(x => x.clave, null, new { @class = "label label-danger" })
                                            </div>

                                            @Html.LabelFor(x => x.telefono, new { @class = "col-sm-1 control-label pull-left" })
                                            <div class="col-md-2">
                                                @Html.TextBoxFor(x => x.telefono, new { @class = "input-12", placeholder = "Telefono" })
                                                @Html.ValidationMessageFor(x => x.telefono, null, new { @class = "label label-danger" })
                                            </div>
                                         </div>

                                        <div class="form-group">
                                            @Html.LabelFor(x => x.foto, new { @class = "col-sm-2 control-label pull-left" })
                                            <div class="col-md-2">
                                                @Html.TextBoxFor(x => x.foto, new { @class = "input-12", placeholder = "Foto" })
                                                @Html.ValidationMessageFor(x => x.foto, null, new { @class = "label label-danger" })
                                            </div>

                                            <div class="col-md-2">
                                                <select name="activo" class="input-12">
                                                    <option @(Model.activo == false ? "selected" : "") value="false"> No Activo </option>
                                                    <option @(Model.activo == true ? "selected" : "") value="true"> Activo </option>
                                                </select>
                                            </div>
                                        </div>
                                    </fieldset>
                                </div>

                            </div>

                        </div>

                    </div>


                    <div class="text-right well well-sm">
                        <button type="submit" data-ajax="true" class="btn btn-primary">Guardar</button>
                    </div>


                </div>

            </div>

        </div>


    </div>



}

proyecto/Areas/Admin/Views/Usuario/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div>
    <a href="~/admin/usuario/crud" class="btn btn-app btn-info btn-xs">
        <i class="ace-icon fa fa-folder-open-o bigger-110"></i>
    </a>

    <a href="~/admin/usuario/index" class="btn btn-app btn-success btn-xs">
        <i class="ace-icon fa fa-exchange bigger-110"></i>
    </a>
</div>

<div id="usuario" class="well">

   

    <div id="list"></div>
</div>



<script>
    $(document).ready(function () {

        $("#list").anexGrid({
            columnas: [
                { leyenda: 'Nombre', columna: 'nombre', ordenable: true },
                { leyenda: 'Correo', columna: 'correo', style: 'width:10px;', ordenable: true },
                 { leyenda: 'Empresa', columna: 'razonsocial', style: 'width:200px;', ordenable: true },
                { leyenda: 'Estado', columna: 'activo', style: 'width:140px;', ordenable: true },
                { style: 'width:10px;' },
                { style: 'width:10px;' }
            ],

            modelo: [
                {
                    propiedad: 'nombre', formato: function (tr, obj, valor) {
                        return anexGrid_link({
                            href: '@Url.Content("~/admin/usuario/crud/")' + obj.idusuario,
                            contenido: valor
                        });
                    }
                },

                { propiedad: 'correo'},

                 { propiedad: 'razonsocial' },

                 {

                     propiedad: 'activo', formato: function (tr, obj, valor) {
                         return valor == true ? "Activo"  : "No Activo";
                         //return anexGrid_link({ href:  })
                     }

                 },




                // BOTONES
                {
                    formato: function (tr, obj, valor) {
                        return anexGrid_link({
                            href: '@Url.Content("~/admin/usuario/crud/")' + obj.idusuario,
                            contenido: 'Visualizar',
                            class: 'btn btn-default btn-xs'
                        });
                    },
                },
                {
                    formato: function (tr, obj, valor) {
                        return anexGrid_link({
                            href: '@Url.Content("~/admin/usuario/eliminar/")' + obj.idusuario,
                            contenido: 'Eliminar',
                            class: 'btn btn-danger btn-xs',
                            attr: [
                                'onclick="return confirm(\'¿Esta seguro de eliminar este registro?\')"'
                            ]
                        });
                    },
                }
            ],

            url: '@Url.Content("~/admin/usuario/cargarUsuario")',
            paginable: true,
            limite: [20, 60, 100],
            columna: 'id',
            columna_orden: 'DESC'
        });
    })
</script>